language: generic

# for permissions
sudo: required

services:
  - docker

before_install:
  # we tag the image so we can reference it
  - docker build -t ceheiss/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ceheiss/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  # Look for it in S3
  bucket_name: 'elasticbeanstalk-eu-central-1-505132125582'
  bucket_path: 'docker-react'
  # only deploy if on master branch
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
